# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            SCEL
tagline:          'Smart Campus Energy Lab'
description:      'The Smart Campus Energy Lab is an innovative, student run research lab with a focus on renewable energy.'
url:              http://scel-dev.com
baseurl:          /

author:
  name:           'Kenny Luong'
  url:            https://twitter.com/kendevr

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/scel-hawaii/scel-dev.org
